appColors = {
        "blue" : "#083D77",
        "lWhite" : "#EBEBD3",
        "yellow" : "#F4D35E",
        "orange" : "#EE964B",
        "mikan" : "#F95738",
        "letter" : "black",
        "letter_button" : "white",
        "letter_buttond" : "black",
        "banner" : "white",
        "syunyu" : "#31aa86",
        "sisyutu" : "#b44567",
        "syunyuB" : "#e0f8d1",
        "sisyutuB" : "#ffeaec",
    }
